// Code generated by MockGen. DO NOT EDIT.
// Source: campaign_repository.go
//
// Generated by this command:
//
//	mockgen -source=campaign_repository.go -destination=mock/mock_campaign_repository.go.gen.go -package=mock_campaign
//

// Package mock_campaign is a generated GoMock package.
package mock_campaign

import (
	context "context"
	campaign "go-boilerplate/internal/domain/campaign"
	uuid "go-boilerplate/pkg/uuid"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CountAll mocks base method.
func (m *MockRepository) CountAll(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountAll", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountAll indicates an expected call of CountAll.
func (mr *MockRepositoryMockRecorder) CountAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountAll", reflect.TypeOf((*MockRepository)(nil).CountAll), ctx)
}

// CountClaims mocks base method.
func (m *MockRepository) CountClaims(ctx context.Context, params campaign.ClaimCountParams) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountClaims", ctx, params)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountClaims indicates an expected call of CountClaims.
func (mr *MockRepositoryMockRecorder) CountClaims(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountClaims", reflect.TypeOf((*MockRepository)(nil).CountClaims), ctx, params)
}

// Create mocks base method.
func (m *MockRepository) Create(ctx context.Context, c *campaign.Campaign) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, c)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRepositoryMockRecorder) Create(ctx, c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepository)(nil).Create), ctx, c)
}

// FindList mocks base method.
func (m *MockRepository) FindList(ctx context.Context, params campaign.ListParams) (campaign.Campaigns, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindList", ctx, params)
	ret0, _ := ret[0].(campaign.Campaigns)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindList indicates an expected call of FindList.
func (mr *MockRepositoryMockRecorder) FindList(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindList", reflect.TypeOf((*MockRepository)(nil).FindList), ctx, params)
}

// LockByCode mocks base method.
func (m *MockRepository) LockByCode(ctx context.Context, code campaign.Code) (*campaign.Campaign, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LockByCode", ctx, code)
	ret0, _ := ret[0].(*campaign.Campaign)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LockByCode indicates an expected call of LockByCode.
func (mr *MockRepositoryMockRecorder) LockByCode(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LockByCode", reflect.TypeOf((*MockRepository)(nil).LockByCode), ctx, code)
}

// LockByID mocks base method.
func (m *MockRepository) LockByID(ctx context.Context, id uuid.UUID) (*campaign.Campaign, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LockByID", ctx, id)
	ret0, _ := ret[0].(*campaign.Campaign)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LockByID indicates an expected call of LockByID.
func (mr *MockRepositoryMockRecorder) LockByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LockByID", reflect.TypeOf((*MockRepository)(nil).LockByID), ctx, id)
}

// RecordClaim mocks base method.
func (m *MockRepository) RecordClaim(ctx context.Context, claim *campaign.Claim) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordClaim", ctx, claim)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordClaim indicates an expected call of RecordClaim.
func (mr *MockRepositoryMockRecorder) RecordClaim(ctx, claim any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordClaim", reflect.TypeOf((*MockRepository)(nil).RecordClaim), ctx, claim)
}

// UpdateSuspended mocks base method.
func (m *MockRepository) UpdateSuspended(ctx context.Context, id uuid.UUID, suspendedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSuspended", ctx, id, suspendedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSuspended indicates an expected call of UpdateSuspended.
func (mr *MockRepositoryMockRecorder) UpdateSuspended(ctx, id, suspendedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSuspended", reflect.TypeOf((*MockRepository)(nil).UpdateSuspended), ctx, id, suspendedAt)
}
