// Code generated by MockGen. DO NOT EDIT.
// Source: campaign_usecase.go
//
// Generated by this command:
//
//	mockgen -source=campaign_usecase.go -destination=mock/mock_campaign_usecase.go.gen.go -package=mock_campaign
//

// Package mock_campaign is a generated GoMock package.
package mock_campaign

import (
	context "context"
	auth "go-boilerplate/internal/usecase/boundary/auth"
	campaign "go-boilerplate/internal/usecase/campaign"
	paging "go-boilerplate/internal/usecase/tools/paging"
	uuid "go-boilerplate/pkg/uuid"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUsecase is a mock of Usecase interface.
type MockUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockUsecaseMockRecorder
	isgomock struct{}
}

// MockUsecaseMockRecorder is the mock recorder for MockUsecase.
type MockUsecaseMockRecorder struct {
	mock *MockUsecase
}

// NewMockUsecase creates a new mock instance.
func NewMockUsecase(ctrl *gomock.Controller) *MockUsecase {
	mock := &MockUsecase{ctrl: ctrl}
	mock.recorder = &MockUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsecase) EXPECT() *MockUsecaseMockRecorder {
	return m.recorder
}

// ClaimCoupon mocks base method.
func (m *MockUsecase) ClaimCoupon(ctx context.Context, authn *auth.Authn, code string) (campaign.ClaimedCouponView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimCoupon", ctx, authn, code)
	ret0, _ := ret[0].(campaign.ClaimedCouponView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClaimCoupon indicates an expected call of ClaimCoupon.
func (mr *MockUsecaseMockRecorder) ClaimCoupon(ctx, authn, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimCoupon", reflect.TypeOf((*MockUsecase)(nil).ClaimCoupon), ctx, authn, code)
}

// DefineCampaign mocks base method.
func (m *MockUsecase) DefineCampaign(ctx context.Context, authn *auth.Authn, params campaign.DefineCampaignParams) (campaign.CampaignView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DefineCampaign", ctx, authn, params)
	ret0, _ := ret[0].(campaign.CampaignView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DefineCampaign indicates an expected call of DefineCampaign.
func (mr *MockUsecaseMockRecorder) DefineCampaign(ctx, authn, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DefineCampaign", reflect.TypeOf((*MockUsecase)(nil).DefineCampaign), ctx, authn, params)
}

// ListCampaigns mocks base method.
func (m *MockUsecase) ListCampaigns(ctx context.Context, authn *auth.Authn, page *paging.Page) (campaign.CampaignListView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCampaigns", ctx, authn, page)
	ret0, _ := ret[0].(campaign.CampaignListView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCampaigns indicates an expected call of ListCampaigns.
func (mr *MockUsecaseMockRecorder) ListCampaigns(ctx, authn, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCampaigns", reflect.TypeOf((*MockUsecase)(nil).ListCampaigns), ctx, authn, page)
}

// SuspendCampaign mocks base method.
func (m *MockUsecase) SuspendCampaign(ctx context.Context, authn *auth.Authn, id uuid.UUID) (campaign.CampaignView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SuspendCampaign", ctx, authn, id)
	ret0, _ := ret[0].(campaign.CampaignView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SuspendCampaign indicates an expected call of SuspendCampaign.
func (mr *MockUsecaseMockRecorder) SuspendCampaign(ctx, authn, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SuspendCampaign", reflect.TypeOf((*MockUsecase)(nil).SuspendCampaign), ctx, authn, id)
}
