// Code generated by MockGen. DO NOT EDIT.
// Source: registrar.go
//
// Generated by this command:
//
//	mockgen -source=registrar.go -destination=mock/mock_registrar.go.gen.go -package=mock_auth
//

// Package mock_auth is a generated GoMock package.
package mock_auth

import (
	context "context"
	uuid "go-boilerplate/pkg/uuid"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIdentityRegistrar is a mock of IdentityRegistrar interface.
type MockIdentityRegistrar struct {
	ctrl     *gomock.Controller
	recorder *MockIdentityRegistrarMockRecorder
	isgomock struct{}
}

// MockIdentityRegistrarMockRecorder is the mock recorder for MockIdentityRegistrar.
type MockIdentityRegistrarMockRecorder struct {
	mock *MockIdentityRegistrar
}

// NewMockIdentityRegistrar creates a new mock instance.
func NewMockIdentityRegistrar(ctrl *gomock.Controller) *MockIdentityRegistrar {
	mock := &MockIdentityRegistrar{ctrl: ctrl}
	mock.recorder = &MockIdentityRegistrarMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIdentityRegistrar) EXPECT() *MockIdentityRegistrarMockRecorder {
	return m.recorder
}

// Register mocks base method.
func (m *MockIdentityRegistrar) Register(ctx context.Context, userID uuid.UUID, issuer, subject string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", ctx, userID, issuer, subject)
	ret0, _ := ret[0].(error)
	return ret0
}

// Register indicates an expected call of Register.
func (mr *MockIdentityRegistrarMockRecorder) Register(ctx, userID, issuer, subject any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockIdentityRegistrar)(nil).Register), ctx, userID, issuer, subject)
}
